# Site settings
title: Minji Kim
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Minji Kim
user_description: 안녕하세요. 웹개발자로서 첫걸음을 시작하는 김민지입니다. 저는 크고 작은 도전들과 함께해 왔습니다. 새로운 것들을 두려워하지 않고 쌓아온 경험들은 제 안의 자산이 되어 빛을 발휘한다고 생각합니다. 처음 자바로 'Hello World'를 출력했던 두근거림은 잊을 수 없을 것입니다. 앞으로도 이렇게 배우고 도전하기를 멈추지 않으며 끊임없이 성장하는 개발자가 되고 싶습니다. 
user_title: A New Web developer
email: kmj87114@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
